### ISSUE TITLE
Gantt like Asana

### ISSUE THREAD

**Issue by ealekseyzev** [highcharts-for-python/highcharts-gantt#51] opened 2024-09-23 06:17 UTC

**Comment by hcpchris** [comment] 2024-09-23 21:37
@ealekseyzev : Sorry, without a description I'm afraid I don't really know what the nature of the issue is. For the time being, I'm closing this issue, but please feel free to re-open it with a more detailed description.

**Closed as not planned by hcpchris** 2024-09-23 21:37 UTC
